#' Function to compare values and statements from 2 linelists
#'
#' @author Amy Mikhail, \email{amy.mikhail@@gmail.com}
#'
#' @description
#' This function takes the values generated by the execsum function for a 
#' current and previous line list, puts them both in a table and compares each 
#' pair of values.  If they are the same, the value assigned to the 'change' 
#' column will be FALSE.  If they are different, the value assigned to the 
#' 'change' column will be TRUE.  Multi-part statements (list of federal states
#' with case numbers and demographic descriptions for deaths) are split for the 
#' comparison.  Two sub-statements are then added to the table, one 
#' representing the values that changed and the other representing the values 
#' that stayed the same.  The change column is used to determine which values
#' get highlighted in the Microsoft word output.
#'
#' @md
#' 
#' @import dplyr
#' @import stringr
#' @import tibble
#' 
#' @param current Table of summary values for the current line list
#' @param previous Table of summary values for the previous line list
#' @param bundeslist List of values and statements for compared bundesland
#' 
#' @return Updated data.frame of placeholder names and values with change flag
#'
#' @examples
#' \donttest{
#' # Create compare table:
#' compare_ll <- compare_table(current = currentvals, 
#'                             previous = previousvals, 
#'                             bundeslist = bundeslist) 
#' }
#' @export
compare_table <- function(current, previous, bundeslist){
  

# Merge and compare current with previous values --------------------------

  
  # Create the comparison table:
  compare = current %>% 
    
    left_join(previous) %>% 
    
    mutate(change = ifelse(value_current == value_previous, FALSE, TRUE)) %>% 
    
    # Add extra rows for splitting the multi-part statements in two:
    tibble::add_row(name = c("bundesland_new_n",
                             "bundesland_new_statement",
                             "bundesland_increased_n",
                             "bundesland_increased_statement",
                             "bundesland_nochange_n",
                             "bundesland_nochange_statement", 
                             "deathsalm_different", 
                             "deathsalm_same", 
                             "deathother_different", 
                             "deathother_same"),
                    value_current = c(bundeslist$newstate_n, 
                                      bundeslist$newstate_statement, 
                                      bundeslist$newcases_n, 
                                      bundeslist$newcases_statement, 
                                      bundeslist$nochange_n, 
                                      bundeslist$nochange_statement, 
                                      NA_character_, 
                                      NA_character_, 
                                      NA_character_, 
                                      NA_character_),
                    change = c(TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, 
                               TRUE, FALSE, 
                               TRUE, FALSE))
  
  
# Function to split multipart statements ----------------------------------
  
  
  split_multipart <- function(compare, statement, prefix){
    
    # Extract the statement from the table:
    current_stat = compare %>% 
      
      filter(name == statement) %>% 
      
      pull(value_current)
    
    # Split the current statement into separate entities:
    curlist = stringr::str_split_1(current_stat, pattern = ", | und ")
    
    # Extract and split the previous statement into separate entities:
    prevlist = compare %>% 
      
      filter(name == statement) %>% 
      
      pull(value_previous) %>% 
      
      stringr::str_split_1(pattern = ", | und ")
    
    # Create a compare table for the separate entities:
    stat_compare = data.frame(current = curlist) %>% 
      
      mutate(change = ifelse(current %in% prevlist, FALSE, TRUE)) %>% 
      
      arrange(desc(change))
    
    # Calculate number of entities which have not changed:
    n_same = stat_compare %>% 
      
      filter(change == FALSE) %>% 
      
      count() %>% 
      
      pull()
    
    
    # Create the new statements:  
    
    # Where there are some entities that have changed and some not:
    if(any(stat_compare$change == TRUE) & any(stat_compare$change == FALSE)) {
      
      # Create a string from places that have changed:
      stat_different = stat_compare %>% 
        
        filter(change == TRUE) %>% 
        
        pull(current) %>% 
        
        stringr::str_flatten_comma(na.rm = TRUE) 
      
      # Create a string from places that did not change:
      stat_same = stat_compare %>% 
        
        filter(change == FALSE) %>% 
        
        pull(current) %>% 
        
        stringr::str_flatten_comma(last = " und ", na.rm = TRUE)
      
      # Deal with end of sentence:
      if(n_same > 1) {
        
        stat_same = paste0(", ", stat_same)
        
      } else {
        
        stat_same = paste0(" und ", stat_same)
        
      } 
      
      # Now if all the places have changed values:
    } else if(all(stat_compare$change == TRUE)) {
      
      stat_different = current_stat
      
      stat_same = ""
      
      # Now if none of the places have changed values:
    } else if(all(stat_compare$change == FALSE)) {
      
      stat_different = ""
      
      stat_same = current_stat
      
    }
    
    
    # Add the new statements to the compare table:  
    compare = compare %>% 
      
      mutate(value_current = case_when(
        
        name == paste0(prefix, "_different") ~ stat_different,
        name == paste0(prefix, "_same")      ~ stat_same,
        TRUE                                 ~ value_current
      ))
    
    # Return updated compare table:
    return(compare)
    
  }
  


# Update compare table with split values ----------------------------------


  # Update compare table with split death due to salmonellosis statement:
  compare = split_multipart(compare = compare,
                            statement = "statement_deaths_salmonella", 
                            prefix = "deathsalm")
  
  # Update compare table with split death due to other causes statement:
  compare = split_multipart(compare = compare,
                            statement = "statement_deaths_other", 
                            prefix = "deathother")
  


# Return compare table ----------------------------------------------------

  return(compare)
  
}
